workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --debug --verbose
    artifacts:
      - build/**/*.apk
    publishing:
      email:
        recipients:
          - yashrajput7766@gmail.com
        notify:
          success: true
          failure: true
